name: Build & Deploy

on:
  push:
    branches: [ "staging1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build Staging App
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        
        script: |
          cd /var/www/bargikrit-bigyapan/staging/frontend
          git checkout .
          git reset --hard origin/staging
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18.17.0
          npm i 
          npm run build
          echo 'Building Staging App'
          pm2 restart bbigyapan_staging_nextjs
          echo 'Build successful'
